<?php

use Illuminate\Database\Seeder;

use App\Models\Venue;
use Faker\Generator as Faker;


class VenuesTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run(Faker $faker)
  {
    // DB::table('venues')->truncate();

    Venue::create([ //1
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => 'サンワールドビル',
      'name_venue' => '1号室',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //2
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => 'サンワールドビル',
      'name_venue' => '2号室',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //3
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '10A',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //4
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '10B',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //5
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '7A',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //6
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '7B',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //7
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '6A',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //8
      'alliance_flag' => 0,
      'name_area' => '四ツ橋',
      'name_bldg' => '近商ビル',
      'name_venue' => '6B',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //9
      'alliance_flag' => 0,
      'name_area' => '本町',
      'name_bldg' => 'カーニープレイス',
      'name_venue' => '4F',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //10
      'alliance_flag' => 0,
      'name_area' => '本町',
      'name_bldg' => 'センタービル',
      'name_venue' => '1号室',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //11
      'alliance_flag' => 0,
      'name_area' => '本町',
      'name_bldg' => 'センタービル',
      'name_venue' => '2号室',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //12
      'alliance_flag' => 0,
      'name_area' => '難波',
      'name_bldg' => '日興ビル',
      'name_venue' => '6F',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //13
      'alliance_flag' => 0,
      'name_area' => '難波',
      'name_bldg' => '日興ビル',
      'name_venue' => 'B2F',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //14
      'alliance_flag' => 0,
      'name_area' => '新大阪',
      'name_bldg' => 'キューホー江坂ビル',
      'name_venue' => '2F',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);
    Venue::create([ //15
      'alliance_flag' => 0,
      'name_area' => '天六',
      'name_bldg' => 'マロニエホール',
      'name_venue' => '7F',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);

    Venue::create([ //16
      'alliance_flag' => 0,
      'name_area' => '心斎橋',
      'name_bldg' => '大成閣',
      'name_venue' => '大ホールA',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);
    Venue::create([ //17
      'alliance_flag' => 0,
      'name_area' => '本町',
      'name_bldg' => '大雅ビル',
      'name_venue' => '第1会議室',
      'size1' => 18,
      'size2' => 50,
      'capacity' => 20,
      'eat_in_flag' => 1,
      'post_code' => '1234567',
      'address1' => 'test',
      'address2' => 'test',
      'address3' => 'test',
      'luggage_flag' => 1,
      'luggage_post_code' => '1234567',
      'luggage_address1' => 'test',
      'luggage_address2' => 'test',
      'luggage_address3' => 'test',
      'luggage_name' => 'test',
      'luggage_tel' => 'test',
      'smg_url' => 'https://osaka-conference.com/rental/',
      'layout' => 1,
      'layout_prepare' => 5000,
      'layout_clean' => 8000
    ]);
  }
}
